[package]
name = "uestc-power-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
uestc-client = { path = "../uestc-client" , version = "0.1.0" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
config = "0.15.19"
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
